### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by fmmsilva** [tj/reds#46]
Is it possible to search using operators like AND, OR, -??

Exaple: 'cars and bikes', 'dogs or cats', 'bike -motorbike'

**Comment by stockholmux** [comment]
You can change the search from `and` to `or`, but not from a query string directly as you wrote. The removal of a keyword (e.g. `-motorbike') is not supported without a lot of extra work.

If you set the `type` on your query instance, you can change it from an `and` to an `or` search:
```
/**
 * Set `type` to "union" or "intersect", aliased as
 * "or" and "and".
 *
 * @param {String} type
 * @return {Query} for chaining
 * @api public
 */

Query.prototype.type = function(type){
  this._type = types[type];
  return this;
};
```

Just an FYI, there will be a new version soon that is a bit more extensible for implementing something a little closer to what you want.

**Comment by fmmsilva** [comment]
Thanks! Watiting for it :)
